// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[id]': typeof import('./components/firestore/[id]/index.vue')['default']
    Auth: typeof import('./components/auth/Auth.vue')['default']
    Collection: typeof import('./components/firestore/Collection.vue')['default']
    CollectionPreview: typeof import('./components/firestore/CollectionPreview.vue')['default']
    Firestore: typeof import('./components/firestore/Firestore.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GuideRoot: typeof import('./components/GuideRoot.vue')['default']
    Header: typeof import('./components/layout-ui/Header.vue')['default']
    HeaderMenu: typeof import('./components/layout-ui/HeaderMenu.vue')['default']
    HeaderNotifications: typeof import('./components/layout-ui/HeaderNotifications.vue')['default']
    HeaderSearch: typeof import('./components/layout-ui/HeaderSearch.vue')['default']
    Home: typeof import('./components/home/Home.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    MobileSidenav: typeof import('./components/layout-ui/MobileSidenav.vue')['default']
    NotificationsPreview: typeof import('./components/home/NotificationsPreview.vue')['default']
    Panel: typeof import('./components/Panel.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResponsiveSidenav: typeof import('./components/layout-ui/ResponsiveSidenav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidenavComponent: typeof import('./components/layout-ui/SidenavComponent.vue')['default']
    SignupPage: typeof import('./components/SignupPage.vue')['default']
    Storage: typeof import('./components/storage/Storage.vue')['default']
  }
}
